version: "3"
services:
    shsodb:
        container_name: shsodb
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./SHSO_sample_DB.sql:/docker-entrypoint-initdb.d/SHSO_sample_DB.sql
    shsoserver:
        container_name: shsoserver
        image: ubuntu:latest
        links:
            - "shsodb"
        build: ./
        working_dir: /home/shsoserver
        command: /bin/sh -c "/home/shsoserver/setup.sh"
        ports:
            - "9339:9339"
            - "9389:9389"
        volumes:
            - ./shso-server/sf-game:/home/shsoserver/sf-game
            - ./shso-server/sf-notification:/home/shsoserver/sf-notification
            - ./setup.sh:/home/shsoserver/setup.sh