version: "3"
services:
    shsodb:
        container_name: shsodb
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./shso-server/SHSO_sample_DB.sql:/docker-entrypoint-initdb.d/SHSO_sample_DB.sql
            - ./dbdata:/var/lib/mysql
    shsoserver:
        container_name: shsoserver
        links:
            - "shsodb"
        working_dir: /home/shsoserver
        volumes:
            - ./shsoserverdata/:/home/shsoadmin
        build: 
            context: ./
            dockerfile: shsoserver/Dockerfile
        ports:
            - "9339:9339"
            - "9389:9389"
        command: /bin/sh -c "cd /home/shsoserver/sf-notification/Server/;./start.sh;cd /home/shsoserver/sf-game/Server/; ./start.sh"